// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: paxos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	NodeID        string                 `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *BallotNumber) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *BallotNumber) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type AcceptRecord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AcceptedBallotNum   *BallotNumber          `protobuf:"bytes,1,opt,name=acceptedBallotNum,proto3" json:"acceptedBallotNum,omitempty"`
	AcceptedSequenceNum int64                  `protobuf:"varint,2,opt,name=acceptedSequenceNum,proto3" json:"acceptedSequenceNum,omitempty"`
	AcceptedVal         *TransactionRequest    `protobuf:"bytes,3,opt,name=acceptedVal,proto3" json:"acceptedVal,omitempty"`
	Committed           bool                   `protobuf:"varint,4,opt,name=Committed,proto3" json:"Committed,omitempty"`
	Executed            bool                   `protobuf:"varint,5,opt,name=Executed,proto3" json:"Executed,omitempty"`
	Result              bool                   `protobuf:"varint,6,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AcceptRecord) Reset() {
	*x = AcceptRecord{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRecord) ProtoMessage() {}

func (x *AcceptRecord) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRecord.ProtoReflect.Descriptor instead.
func (*AcceptRecord) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptRecord) GetAcceptedBallotNum() *BallotNumber {
	if x != nil {
		return x.AcceptedBallotNum
	}
	return nil
}

func (x *AcceptRecord) GetAcceptedSequenceNum() int64 {
	if x != nil {
		return x.AcceptedSequenceNum
	}
	return 0
}

func (x *AcceptRecord) GetAcceptedVal() *TransactionRequest {
	if x != nil {
		return x.AcceptedVal
	}
	return nil
}

func (x *AcceptRecord) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *AcceptRecord) GetExecuted() bool {
	if x != nil {
		return x.Executed
	}
	return false
}

func (x *AcceptRecord) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	AcceptNum     *BallotNumber          `protobuf:"bytes,2,opt,name=acceptNum,proto3" json:"acceptNum,omitempty"`
	AcceptLog     []*AcceptRecord        `protobuf:"bytes,3,rep,name=acceptLog,proto3" json:"acceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AckMessage) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AckMessage) GetAcceptNum() *BallotNumber {
	if x != nil {
		return x.AcceptNum
	}
	return nil
}

func (x *AckMessage) GetAcceptLog() []*AcceptRecord {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Message       *TransactionRequest    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *AcceptMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptMessage) GetMessage() *TransactionRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	B             *BallotNumber          `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,3,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Message       *TransactionRequest    `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	AcceptorID    string                 `protobuf:"bytes,5,opt,name=acceptorID,proto3" json:"acceptorID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptedMessage) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcceptedMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *AcceptedMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptedMessage) GetMessage() *TransactionRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AcceptedMessage) GetAcceptorID() string {
	if x != nil {
		return x.AcceptorID
	}
	return ""
}

type NewViewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	AcceptLog     []*AcceptRecord        `protobuf:"bytes,2,rep,name=acceptLog,proto3" json:"acceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMessage) Reset() {
	*x = NewViewMessage{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMessage) ProtoMessage() {}

func (x *NewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMessage.ProtoReflect.Descriptor instead.
func (*NewViewMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *NewViewMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *NewViewMessage) GetAcceptLog() []*AcceptRecord {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type CommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Transaction   *TransactionRequest    `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *CommitMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *CommitMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CommitMessage) GetTransaction() *TransactionRequest {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CatchupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	AcceptLog     []*AcceptRecord        `protobuf:"bytes,2,rep,name=acceptLog,proto3" json:"acceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupMessage) Reset() {
	*x = CatchupMessage{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupMessage) ProtoMessage() {}

func (x *CatchupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupMessage.ProtoReflect.Descriptor instead.
func (*CatchupMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *CatchupMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *CatchupMessage) GetAcceptLog() []*AcceptRecord {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Result        bool                   `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionResponse) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *TransactionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x12\x05paxos\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"4\n" +
	"\fBallotNumber\x12\f\n" +
	"\x01n\x18\x01 \x01(\x03R\x01n\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\tR\x06nodeID\"\x92\x02\n" +
	"\fAcceptRecord\x12A\n" +
	"\x11acceptedBallotNum\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x11acceptedBallotNum\x120\n" +
	"\x13acceptedSequenceNum\x18\x02 \x01(\x03R\x13acceptedSequenceNum\x12;\n" +
	"\vacceptedVal\x18\x03 \x01(\v2\x19.paxos.TransactionRequestR\vacceptedVal\x12\x1c\n" +
	"\tCommitted\x18\x04 \x01(\bR\tCommitted\x12\x1a\n" +
	"\bExecuted\x18\x05 \x01(\bR\bExecuted\x12\x16\n" +
	"\x06Result\x18\x06 \x01(\bR\x06Result\"3\n" +
	"\x0ePrepareMessage\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x01b\"\x82\x01\n" +
	"\n" +
	"AckMessage\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\tacceptNum\x18\x02 \x01(\v2\x13.paxos.BallotNumberR\tacceptNum\x121\n" +
	"\tacceptLog\x18\x03 \x03(\v2\x13.paxos.AcceptRecordR\tacceptLog\"\x89\x01\n" +
	"\rAcceptMessage\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x123\n" +
	"\amessage\x18\x03 \x01(\v2\x19.paxos.TransactionRequestR\amessage\"\xbb\x01\n" +
	"\x0fAcceptedMessage\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\x01b\x18\x02 \x01(\v2\x13.paxos.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x03 \x01(\x03R\vsequenceNum\x123\n" +
	"\amessage\x18\x04 \x01(\v2\x19.paxos.TransactionRequestR\amessage\x12\x1e\n" +
	"\n" +
	"acceptorID\x18\x05 \x01(\tR\n" +
	"acceptorID\"f\n" +
	"\x0eNewViewMessage\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x01b\x121\n" +
	"\tacceptLog\x18\x02 \x03(\v2\x13.paxos.AcceptRecordR\tacceptLog\"\x91\x01\n" +
	"\rCommitMessage\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12;\n" +
	"\vtransaction\x18\x03 \x01(\v2\x19.paxos.TransactionRequestR\vtransaction\"f\n" +
	"\x0eCatchupMessage\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x01b\x121\n" +
	"\tacceptLog\x18\x02 \x03(\v2\x13.paxos.AcceptRecordR\tacceptLog\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\x80\x01\n" +
	"\x12TransactionRequest\x124\n" +
	"\vtransaction\x18\x01 \x01(\v2\x12.paxos.TransactionR\vtransaction\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\"\x86\x01\n" +
	"\x13TransactionResponse\x12!\n" +
	"\x01b\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x01b\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x16\n" +
	"\x06result\x18\x04 \x01(\bR\x06result2\xd5\x06\n" +
	"\x05Paxos\x12H\n" +
	"\x0fTransferRequest\x12\x19.paxos.TransactionRequest\x1a\x1a.paxos.TransactionResponse\x12:\n" +
	"\x0ePrepareRequest\x12\x15.paxos.PrepareMessage\x1a\x11.paxos.AckMessage\x12A\n" +
	"\x0eNewViewRequest\x12\x15.paxos.NewViewMessage\x1a\x16.paxos.AcceptedMessage0\x01\x12=\n" +
	"\rAcceptRequest\x12\x14.paxos.AcceptMessage\x1a\x16.paxos.AcceptedMessage\x12=\n" +
	"\rCommitRequest\x12\x14.paxos.CommitMessage\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x0eCatchupRequest\x12\x1b.google.protobuf.Int64Value\x1a\x15.paxos.CatchupMessage\x12F\n" +
	"\x10ChangeNodeStatus\x12\x1a.google.protobuf.BoolValue\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"KillLeader\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bPrintLog\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aPrintDB\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vPrintStatus\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\tPrintView\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x0fPrintTimerState\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB5Z3github.com/mavleo96/stable-leader-paxos/pb/paxos;pbb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_paxos_proto_goTypes = []any{
	(*BallotNumber)(nil),          // 0: paxos.BallotNumber
	(*AcceptRecord)(nil),          // 1: paxos.AcceptRecord
	(*PrepareMessage)(nil),        // 2: paxos.PrepareMessage
	(*AckMessage)(nil),            // 3: paxos.AckMessage
	(*AcceptMessage)(nil),         // 4: paxos.AcceptMessage
	(*AcceptedMessage)(nil),       // 5: paxos.AcceptedMessage
	(*NewViewMessage)(nil),        // 6: paxos.NewViewMessage
	(*CommitMessage)(nil),         // 7: paxos.CommitMessage
	(*CatchupMessage)(nil),        // 8: paxos.CatchupMessage
	(*Transaction)(nil),           // 9: paxos.Transaction
	(*TransactionRequest)(nil),    // 10: paxos.TransactionRequest
	(*TransactionResponse)(nil),   // 11: paxos.TransactionResponse
	(*wrapperspb.Int64Value)(nil), // 12: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),  // 13: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_paxos_proto_depIdxs = []int32{
	0,  // 0: paxos.AcceptRecord.acceptedBallotNum:type_name -> paxos.BallotNumber
	10, // 1: paxos.AcceptRecord.acceptedVal:type_name -> paxos.TransactionRequest
	0,  // 2: paxos.PrepareMessage.b:type_name -> paxos.BallotNumber
	0,  // 3: paxos.AckMessage.acceptNum:type_name -> paxos.BallotNumber
	1,  // 4: paxos.AckMessage.acceptLog:type_name -> paxos.AcceptRecord
	0,  // 5: paxos.AcceptMessage.b:type_name -> paxos.BallotNumber
	10, // 6: paxos.AcceptMessage.message:type_name -> paxos.TransactionRequest
	0,  // 7: paxos.AcceptedMessage.b:type_name -> paxos.BallotNumber
	10, // 8: paxos.AcceptedMessage.message:type_name -> paxos.TransactionRequest
	0,  // 9: paxos.NewViewMessage.b:type_name -> paxos.BallotNumber
	1,  // 10: paxos.NewViewMessage.acceptLog:type_name -> paxos.AcceptRecord
	0,  // 11: paxos.CommitMessage.b:type_name -> paxos.BallotNumber
	10, // 12: paxos.CommitMessage.transaction:type_name -> paxos.TransactionRequest
	0,  // 13: paxos.CatchupMessage.b:type_name -> paxos.BallotNumber
	1,  // 14: paxos.CatchupMessage.acceptLog:type_name -> paxos.AcceptRecord
	9,  // 15: paxos.TransactionRequest.transaction:type_name -> paxos.Transaction
	0,  // 16: paxos.TransactionResponse.b:type_name -> paxos.BallotNumber
	10, // 17: paxos.Paxos.TransferRequest:input_type -> paxos.TransactionRequest
	2,  // 18: paxos.Paxos.PrepareRequest:input_type -> paxos.PrepareMessage
	6,  // 19: paxos.Paxos.NewViewRequest:input_type -> paxos.NewViewMessage
	4,  // 20: paxos.Paxos.AcceptRequest:input_type -> paxos.AcceptMessage
	7,  // 21: paxos.Paxos.CommitRequest:input_type -> paxos.CommitMessage
	12, // 22: paxos.Paxos.CatchupRequest:input_type -> google.protobuf.Int64Value
	13, // 23: paxos.Paxos.ChangeNodeStatus:input_type -> google.protobuf.BoolValue
	14, // 24: paxos.Paxos.KillLeader:input_type -> google.protobuf.Empty
	14, // 25: paxos.Paxos.PrintLog:input_type -> google.protobuf.Empty
	14, // 26: paxos.Paxos.PrintDB:input_type -> google.protobuf.Empty
	12, // 27: paxos.Paxos.PrintStatus:input_type -> google.protobuf.Int64Value
	14, // 28: paxos.Paxos.PrintView:input_type -> google.protobuf.Empty
	14, // 29: paxos.Paxos.PrintTimerState:input_type -> google.protobuf.Empty
	11, // 30: paxos.Paxos.TransferRequest:output_type -> paxos.TransactionResponse
	3,  // 31: paxos.Paxos.PrepareRequest:output_type -> paxos.AckMessage
	5,  // 32: paxos.Paxos.NewViewRequest:output_type -> paxos.AcceptedMessage
	5,  // 33: paxos.Paxos.AcceptRequest:output_type -> paxos.AcceptedMessage
	14, // 34: paxos.Paxos.CommitRequest:output_type -> google.protobuf.Empty
	8,  // 35: paxos.Paxos.CatchupRequest:output_type -> paxos.CatchupMessage
	14, // 36: paxos.Paxos.ChangeNodeStatus:output_type -> google.protobuf.Empty
	14, // 37: paxos.Paxos.KillLeader:output_type -> google.protobuf.Empty
	14, // 38: paxos.Paxos.PrintLog:output_type -> google.protobuf.Empty
	14, // 39: paxos.Paxos.PrintDB:output_type -> google.protobuf.Empty
	14, // 40: paxos.Paxos.PrintStatus:output_type -> google.protobuf.Empty
	14, // 41: paxos.Paxos.PrintView:output_type -> google.protobuf.Empty
	14, // 42: paxos.Paxos.PrintTimerState:output_type -> google.protobuf.Empty
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
