// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: paxos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestSet       int64                  `protobuf:"varint,1,opt,name=testSet,proto3" json:"testSet,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetTestSet() int64 {
	if x != nil {
		return x.TestSet
	}
	return 0
}

func (x *StatusRequest) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitBalance   int64                  `protobuf:"varint,1,opt,name=initBalance,proto3" json:"initBalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *ResetRequest) GetInitBalance() int64 {
	if x != nil {
		return x.InitBalance
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Result        bool                   `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionResponse) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *TransactionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	AcceptLog     []*AcceptedMessage     `protobuf:"bytes,3,rep,name=acceptLog,proto3" json:"acceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *AckMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *AckMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AckMessage) GetAcceptLog() []*AcceptedMessage {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	NodeID        string                 `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *BallotNumber) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *BallotNumber) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Message       *TransactionRequest    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *AcceptMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptMessage) GetMessage() *TransactionRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Message       *TransactionRequest    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptedMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *AcceptedMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptedMessage) GetMessage() *TransactionRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AcceptedMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type CommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Message       *TransactionRequest    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *CommitMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *CommitMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CommitMessage) GetMessage() *TransactionRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

type CheckpointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   int64                  `protobuf:"varint,1,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMessage) Reset() {
	*x = CheckpointMessage{}
	mi := &file_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMessage) ProtoMessage() {}

func (x *CheckpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMessage.ProtoReflect.Descriptor instead.
func (*CheckpointMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *CheckpointMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CheckpointMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type GetCheckpointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   int64                  `protobuf:"varint,1,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	NodeID        string                 `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointMessage) Reset() {
	*x = GetCheckpointMessage{}
	mi := &file_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointMessage) ProtoMessage() {}

func (x *GetCheckpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointMessage.ProtoReflect.Descriptor instead.
func (*GetCheckpointMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *GetCheckpointMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *GetCheckpointMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type Checkpoint struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum         int64                  `protobuf:"varint,1,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest              []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Snapshot            map[string]int64       `protobuf:"bytes,3,rep,name=snapshot,proto3" json:"snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DedupTableTimestamp map[string]int64       `protobuf:"bytes,4,rep,name=dedupTableTimestamp,proto3" json:"dedupTableTimestamp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DedupTableResult    map[string]int64       `protobuf:"bytes,5,rep,name=dedupTableResult,proto3" json:"dedupTableResult,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{13}
}

func (x *Checkpoint) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *Checkpoint) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Checkpoint) GetSnapshot() map[string]int64 {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Checkpoint) GetDedupTableTimestamp() map[string]int64 {
	if x != nil {
		return x.DedupTableTimestamp
	}
	return nil
}

func (x *Checkpoint) GetDedupTableResult() map[string]int64 {
	if x != nil {
		return x.DedupTableResult
	}
	return nil
}

type NewViewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	AcceptLog     []*AcceptMessage       `protobuf:"bytes,3,rep,name=acceptLog,proto3" json:"acceptLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMessage) Reset() {
	*x = NewViewMessage{}
	mi := &file_paxos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMessage) ProtoMessage() {}

func (x *NewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMessage.ProtoReflect.Descriptor instead.
func (*NewViewMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{14}
}

func (x *NewViewMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *NewViewMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *NewViewMessage) GetAcceptLog() []*AcceptMessage {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type CatchupRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupRequestMessage) Reset() {
	*x = CatchupRequestMessage{}
	mi := &file_paxos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupRequestMessage) ProtoMessage() {}

func (x *CatchupRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupRequestMessage.ProtoReflect.Descriptor instead.
func (*CatchupRequestMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{15}
}

func (x *CatchupRequestMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *CatchupRequestMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type CatchupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *BallotNumber          `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	CommitLog     []*CommitMessage       `protobuf:"bytes,3,rep,name=commitLog,proto3" json:"commitLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupMessage) Reset() {
	*x = CatchupMessage{}
	mi := &file_paxos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupMessage) ProtoMessage() {}

func (x *CatchupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupMessage.ProtoReflect.Descriptor instead.
func (*CatchupMessage) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{16}
}

func (x *CatchupMessage) GetB() *BallotNumber {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *CatchupMessage) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *CatchupMessage) GetCommitLog() []*CommitMessage {
	if x != nil {
		return x.CommitLog
	}
	return nil
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"K\n" +
	"\rStatusRequest\x12\x18\n" +
	"\atestSet\x18\x01 \x01(\x03R\atestSet\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\"0\n" +
	"\fResetRequest\x12 \n" +
	"\vinitBalance\x18\x01 \x01(\x03R\vinitBalance\"\x83\x01\n" +
	"\x13TransactionResponse\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x16\n" +
	"\x06result\x18\x04 \x01(\bR\x06result\"}\n" +
	"\x12TransactionRequest\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"0\n" +
	"\x0ePrepareMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\"\x81\x01\n" +
	"\n" +
	"AckMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x121\n" +
	"\tacceptLog\x18\x03 \x03(\v2\x13.pb.AcceptedMessageR\tacceptLog\"4\n" +
	"\fBallotNumber\x12\f\n" +
	"\x01n\x18\x01 \x01(\x03R\x01n\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\tR\x06nodeID\"\x83\x01\n" +
	"\rAcceptMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x120\n" +
	"\amessage\x18\x03 \x01(\v2\x16.pb.TransactionRequestR\amessage\"\x9d\x01\n" +
	"\x0fAcceptedMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x120\n" +
	"\amessage\x18\x03 \x01(\v2\x16.pb.TransactionRequestR\amessage\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\"\x83\x01\n" +
	"\rCommitMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x120\n" +
	"\amessage\x18\x03 \x01(\v2\x16.pb.TransactionRequestR\amessage\"M\n" +
	"\x11CheckpointMessage\x12 \n" +
	"\vsequenceNum\x18\x01 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"P\n" +
	"\x14GetCheckpointMessage\x12 \n" +
	"\vsequenceNum\x18\x01 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\tR\x06nodeID\"\xf7\x03\n" +
	"\n" +
	"Checkpoint\x12 \n" +
	"\vsequenceNum\x18\x01 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x128\n" +
	"\bsnapshot\x18\x03 \x03(\v2\x1c.pb.Checkpoint.SnapshotEntryR\bsnapshot\x12Y\n" +
	"\x13dedupTableTimestamp\x18\x04 \x03(\v2'.pb.Checkpoint.DedupTableTimestampEntryR\x13dedupTableTimestamp\x12P\n" +
	"\x10dedupTableResult\x18\x05 \x03(\v2$.pb.Checkpoint.DedupTableResultEntryR\x10dedupTableResult\x1a;\n" +
	"\rSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aF\n" +
	"\x18DedupTableTimestampEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15DedupTableResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x83\x01\n" +
	"\x0eNewViewMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12/\n" +
	"\tacceptLog\x18\x03 \x03(\v2\x11.pb.AcceptMessageR\tacceptLog\"Q\n" +
	"\x15CatchupRequestMessage\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\"\x91\x01\n" +
	"\x0eCatchupMessage\x12\x1e\n" +
	"\x01b\x18\x01 \x01(\v2\x10.pb.BallotNumberR\x01b\x12.\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x0e.pb.CheckpointR\n" +
	"checkpoint\x12/\n" +
	"\tcommitLog\x18\x03 \x03(\v2\x11.pb.CommitMessageR\tcommitLog2\xf2\a\n" +
	"\tPaxosNode\x12B\n" +
	"\x0fTransferRequest\x12\x16.pb.TransactionRequest\x1a\x17.pb.TransactionResponse\x12@\n" +
	"\x0eForwardRequest\x12\x16.pb.TransactionRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x0ePrepareRequest\x12\x12.pb.PrepareMessage\x1a\x0e.pb.AckMessage\x127\n" +
	"\rAcceptRequest\x12\x11.pb.AcceptMessage\x1a\x13.pb.AcceptedMessage\x12:\n" +
	"\rCommitRequest\x12\x11.pb.CommitMessage\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x11CheckpointRequest\x12\x15.pb.CheckpointMessage\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x0eNewViewRequest\x12\x12.pb.NewViewMessage\x1a\x13.pb.AcceptedMessage0\x01\x12?\n" +
	"\x0eCatchupRequest\x12\x19.pb.CatchupRequestMessage\x1a\x12.pb.CatchupMessage\x129\n" +
	"\rGetCheckpoint\x12\x18.pb.GetCheckpointMessage\x1a\x0e.pb.Checkpoint\x12?\n" +
	"\bPrintLog\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\aPrintDB\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x128\n" +
	"\vPrintStatus\x12\x11.pb.StatusRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\tPrintView\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x0fReconfigureNode\x12\x1a.google.protobuf.BoolValue\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"KillLeader\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x125\n" +
	"\tResetNode\x12\x10.pb.ResetRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/mavleo96/stable-leader-paxos/pbb\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_paxos_proto_goTypes = []any{
	(*StatusRequest)(nil),         // 0: pb.StatusRequest
	(*ResetRequest)(nil),          // 1: pb.ResetRequest
	(*TransactionResponse)(nil),   // 2: pb.TransactionResponse
	(*TransactionRequest)(nil),    // 3: pb.TransactionRequest
	(*Transaction)(nil),           // 4: pb.Transaction
	(*PrepareMessage)(nil),        // 5: pb.PrepareMessage
	(*AckMessage)(nil),            // 6: pb.AckMessage
	(*BallotNumber)(nil),          // 7: pb.BallotNumber
	(*AcceptMessage)(nil),         // 8: pb.AcceptMessage
	(*AcceptedMessage)(nil),       // 9: pb.AcceptedMessage
	(*CommitMessage)(nil),         // 10: pb.CommitMessage
	(*CheckpointMessage)(nil),     // 11: pb.CheckpointMessage
	(*GetCheckpointMessage)(nil),  // 12: pb.GetCheckpointMessage
	(*Checkpoint)(nil),            // 13: pb.Checkpoint
	(*NewViewMessage)(nil),        // 14: pb.NewViewMessage
	(*CatchupRequestMessage)(nil), // 15: pb.CatchupRequestMessage
	(*CatchupMessage)(nil),        // 16: pb.CatchupMessage
	nil,                           // 17: pb.Checkpoint.SnapshotEntry
	nil,                           // 18: pb.Checkpoint.DedupTableTimestampEntry
	nil,                           // 19: pb.Checkpoint.DedupTableResultEntry
	(*wrapperspb.Int64Value)(nil), // 20: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),  // 21: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),         // 22: google.protobuf.Empty
}
var file_paxos_proto_depIdxs = []int32{
	7,  // 0: pb.TransactionResponse.b:type_name -> pb.BallotNumber
	4,  // 1: pb.TransactionRequest.transaction:type_name -> pb.Transaction
	7,  // 2: pb.PrepareMessage.b:type_name -> pb.BallotNumber
	7,  // 3: pb.AckMessage.b:type_name -> pb.BallotNumber
	9,  // 4: pb.AckMessage.acceptLog:type_name -> pb.AcceptedMessage
	7,  // 5: pb.AcceptMessage.b:type_name -> pb.BallotNumber
	3,  // 6: pb.AcceptMessage.message:type_name -> pb.TransactionRequest
	7,  // 7: pb.AcceptedMessage.b:type_name -> pb.BallotNumber
	3,  // 8: pb.AcceptedMessage.message:type_name -> pb.TransactionRequest
	7,  // 9: pb.CommitMessage.b:type_name -> pb.BallotNumber
	3,  // 10: pb.CommitMessage.message:type_name -> pb.TransactionRequest
	17, // 11: pb.Checkpoint.snapshot:type_name -> pb.Checkpoint.SnapshotEntry
	18, // 12: pb.Checkpoint.dedupTableTimestamp:type_name -> pb.Checkpoint.DedupTableTimestampEntry
	19, // 13: pb.Checkpoint.dedupTableResult:type_name -> pb.Checkpoint.DedupTableResultEntry
	7,  // 14: pb.NewViewMessage.b:type_name -> pb.BallotNumber
	8,  // 15: pb.NewViewMessage.acceptLog:type_name -> pb.AcceptMessage
	7,  // 16: pb.CatchupMessage.b:type_name -> pb.BallotNumber
	13, // 17: pb.CatchupMessage.checkpoint:type_name -> pb.Checkpoint
	10, // 18: pb.CatchupMessage.commitLog:type_name -> pb.CommitMessage
	3,  // 19: pb.PaxosNode.TransferRequest:input_type -> pb.TransactionRequest
	3,  // 20: pb.PaxosNode.ForwardRequest:input_type -> pb.TransactionRequest
	5,  // 21: pb.PaxosNode.PrepareRequest:input_type -> pb.PrepareMessage
	8,  // 22: pb.PaxosNode.AcceptRequest:input_type -> pb.AcceptMessage
	10, // 23: pb.PaxosNode.CommitRequest:input_type -> pb.CommitMessage
	11, // 24: pb.PaxosNode.CheckpointRequest:input_type -> pb.CheckpointMessage
	14, // 25: pb.PaxosNode.NewViewRequest:input_type -> pb.NewViewMessage
	15, // 26: pb.PaxosNode.CatchupRequest:input_type -> pb.CatchupRequestMessage
	12, // 27: pb.PaxosNode.GetCheckpoint:input_type -> pb.GetCheckpointMessage
	20, // 28: pb.PaxosNode.PrintLog:input_type -> google.protobuf.Int64Value
	20, // 29: pb.PaxosNode.PrintDB:input_type -> google.protobuf.Int64Value
	0,  // 30: pb.PaxosNode.PrintStatus:input_type -> pb.StatusRequest
	20, // 31: pb.PaxosNode.PrintView:input_type -> google.protobuf.Int64Value
	21, // 32: pb.PaxosNode.ReconfigureNode:input_type -> google.protobuf.BoolValue
	22, // 33: pb.PaxosNode.KillLeader:input_type -> google.protobuf.Empty
	1,  // 34: pb.PaxosNode.ResetNode:input_type -> pb.ResetRequest
	2,  // 35: pb.PaxosNode.TransferRequest:output_type -> pb.TransactionResponse
	22, // 36: pb.PaxosNode.ForwardRequest:output_type -> google.protobuf.Empty
	6,  // 37: pb.PaxosNode.PrepareRequest:output_type -> pb.AckMessage
	9,  // 38: pb.PaxosNode.AcceptRequest:output_type -> pb.AcceptedMessage
	22, // 39: pb.PaxosNode.CommitRequest:output_type -> google.protobuf.Empty
	22, // 40: pb.PaxosNode.CheckpointRequest:output_type -> google.protobuf.Empty
	9,  // 41: pb.PaxosNode.NewViewRequest:output_type -> pb.AcceptedMessage
	16, // 42: pb.PaxosNode.CatchupRequest:output_type -> pb.CatchupMessage
	13, // 43: pb.PaxosNode.GetCheckpoint:output_type -> pb.Checkpoint
	22, // 44: pb.PaxosNode.PrintLog:output_type -> google.protobuf.Empty
	22, // 45: pb.PaxosNode.PrintDB:output_type -> google.protobuf.Empty
	22, // 46: pb.PaxosNode.PrintStatus:output_type -> google.protobuf.Empty
	22, // 47: pb.PaxosNode.PrintView:output_type -> google.protobuf.Empty
	22, // 48: pb.PaxosNode.ReconfigureNode:output_type -> google.protobuf.Empty
	22, // 49: pb.PaxosNode.KillLeader:output_type -> google.protobuf.Empty
	22, // 50: pb.PaxosNode.ResetNode:output_type -> google.protobuf.Empty
	35, // [35:51] is the sub-list for method output_type
	19, // [19:35] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
