// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: paxos.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PaxosNode_TransferRequest_FullMethodName   = "/pb.PaxosNode/TransferRequest"
	PaxosNode_ForwardRequest_FullMethodName    = "/pb.PaxosNode/ForwardRequest"
	PaxosNode_PrepareRequest_FullMethodName    = "/pb.PaxosNode/PrepareRequest"
	PaxosNode_AcceptRequest_FullMethodName     = "/pb.PaxosNode/AcceptRequest"
	PaxosNode_CommitRequest_FullMethodName     = "/pb.PaxosNode/CommitRequest"
	PaxosNode_CheckpointRequest_FullMethodName = "/pb.PaxosNode/CheckpointRequest"
	PaxosNode_NewViewRequest_FullMethodName    = "/pb.PaxosNode/NewViewRequest"
	PaxosNode_CatchupRequest_FullMethodName    = "/pb.PaxosNode/CatchupRequest"
	PaxosNode_GetCheckpoint_FullMethodName     = "/pb.PaxosNode/GetCheckpoint"
	PaxosNode_PrintLog_FullMethodName          = "/pb.PaxosNode/PrintLog"
	PaxosNode_PrintDB_FullMethodName           = "/pb.PaxosNode/PrintDB"
	PaxosNode_PrintStatus_FullMethodName       = "/pb.PaxosNode/PrintStatus"
	PaxosNode_PrintView_FullMethodName         = "/pb.PaxosNode/PrintView"
	PaxosNode_ReconfigureNode_FullMethodName   = "/pb.PaxosNode/ReconfigureNode"
	PaxosNode_KillLeader_FullMethodName        = "/pb.PaxosNode/KillLeader"
	PaxosNode_ResetNode_FullMethodName         = "/pb.PaxosNode/ResetNode"
)

// PaxosNodeClient is the client API for PaxosNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosNodeClient interface {
	TransferRequest(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	ForwardRequest(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrepareRequest(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*AckMessage, error)
	AcceptRequest(ctx context.Context, in *AcceptMessage, opts ...grpc.CallOption) (*AcceptedMessage, error)
	CommitRequest(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CheckpointRequest(ctx context.Context, in *CheckpointMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NewViewRequest(ctx context.Context, in *NewViewMessage, opts ...grpc.CallOption) (PaxosNode_NewViewRequestClient, error)
	CatchupRequest(ctx context.Context, in *CatchupRequestMessage, opts ...grpc.CallOption) (*CatchupMessage, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointMessage, opts ...grpc.CallOption) (*Checkpoint, error)
	PrintLog(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrintDB(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrintStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrintView(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReconfigureNode(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KillLeader(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResetNode(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type paxosNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosNodeClient(cc grpc.ClientConnInterface) PaxosNodeClient {
	return &paxosNodeClient{cc}
}

func (c *paxosNodeClient) TransferRequest(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, PaxosNode_TransferRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) ForwardRequest(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_ForwardRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrepareRequest(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*AckMessage, error) {
	out := new(AckMessage)
	err := c.cc.Invoke(ctx, PaxosNode_PrepareRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) AcceptRequest(ctx context.Context, in *AcceptMessage, opts ...grpc.CallOption) (*AcceptedMessage, error) {
	out := new(AcceptedMessage)
	err := c.cc.Invoke(ctx, PaxosNode_AcceptRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) CommitRequest(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_CommitRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) CheckpointRequest(ctx context.Context, in *CheckpointMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_CheckpointRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) NewViewRequest(ctx context.Context, in *NewViewMessage, opts ...grpc.CallOption) (PaxosNode_NewViewRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &PaxosNode_ServiceDesc.Streams[0], PaxosNode_NewViewRequest_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &paxosNodeNewViewRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PaxosNode_NewViewRequestClient interface {
	Recv() (*AcceptedMessage, error)
	grpc.ClientStream
}

type paxosNodeNewViewRequestClient struct {
	grpc.ClientStream
}

func (x *paxosNodeNewViewRequestClient) Recv() (*AcceptedMessage, error) {
	m := new(AcceptedMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *paxosNodeClient) CatchupRequest(ctx context.Context, in *CatchupRequestMessage, opts ...grpc.CallOption) (*CatchupMessage, error) {
	out := new(CatchupMessage)
	err := c.cc.Invoke(ctx, PaxosNode_CatchupRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetCheckpoint(ctx context.Context, in *GetCheckpointMessage, opts ...grpc.CallOption) (*Checkpoint, error) {
	out := new(Checkpoint)
	err := c.cc.Invoke(ctx, PaxosNode_GetCheckpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintLog(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_PrintLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintDB(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_PrintDB_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_PrintStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintView(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_PrintView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) ReconfigureNode(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_ReconfigureNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) KillLeader(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_KillLeader_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) ResetNode(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaxosNode_ResetNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosNodeServer is the server API for PaxosNode service.
// All implementations must embed UnimplementedPaxosNodeServer
// for forward compatibility
type PaxosNodeServer interface {
	TransferRequest(context.Context, *TransactionRequest) (*TransactionResponse, error)
	ForwardRequest(context.Context, *TransactionRequest) (*emptypb.Empty, error)
	PrepareRequest(context.Context, *PrepareMessage) (*AckMessage, error)
	AcceptRequest(context.Context, *AcceptMessage) (*AcceptedMessage, error)
	CommitRequest(context.Context, *CommitMessage) (*emptypb.Empty, error)
	CheckpointRequest(context.Context, *CheckpointMessage) (*emptypb.Empty, error)
	NewViewRequest(*NewViewMessage, PaxosNode_NewViewRequestServer) error
	CatchupRequest(context.Context, *CatchupRequestMessage) (*CatchupMessage, error)
	GetCheckpoint(context.Context, *GetCheckpointMessage) (*Checkpoint, error)
	PrintLog(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	PrintDB(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	PrintStatus(context.Context, *StatusRequest) (*emptypb.Empty, error)
	PrintView(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	ReconfigureNode(context.Context, *wrapperspb.BoolValue) (*emptypb.Empty, error)
	KillLeader(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ResetNode(context.Context, *ResetRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPaxosNodeServer()
}

// UnimplementedPaxosNodeServer must be embedded to have forward compatible implementations.
type UnimplementedPaxosNodeServer struct {
}

func (UnimplementedPaxosNodeServer) TransferRequest(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferRequest not implemented")
}
func (UnimplementedPaxosNodeServer) ForwardRequest(context.Context, *TransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardRequest not implemented")
}
func (UnimplementedPaxosNodeServer) PrepareRequest(context.Context, *PrepareMessage) (*AckMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareRequest not implemented")
}
func (UnimplementedPaxosNodeServer) AcceptRequest(context.Context, *AcceptMessage) (*AcceptedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptRequest not implemented")
}
func (UnimplementedPaxosNodeServer) CommitRequest(context.Context, *CommitMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitRequest not implemented")
}
func (UnimplementedPaxosNodeServer) CheckpointRequest(context.Context, *CheckpointMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckpointRequest not implemented")
}
func (UnimplementedPaxosNodeServer) NewViewRequest(*NewViewMessage, PaxosNode_NewViewRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method NewViewRequest not implemented")
}
func (UnimplementedPaxosNodeServer) CatchupRequest(context.Context, *CatchupRequestMessage) (*CatchupMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CatchupRequest not implemented")
}
func (UnimplementedPaxosNodeServer) GetCheckpoint(context.Context, *GetCheckpointMessage) (*Checkpoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedPaxosNodeServer) PrintLog(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedPaxosNodeServer) PrintDB(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedPaxosNodeServer) PrintStatus(context.Context, *StatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintStatus not implemented")
}
func (UnimplementedPaxosNodeServer) PrintView(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintView not implemented")
}
func (UnimplementedPaxosNodeServer) ReconfigureNode(context.Context, *wrapperspb.BoolValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconfigureNode not implemented")
}
func (UnimplementedPaxosNodeServer) KillLeader(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillLeader not implemented")
}
func (UnimplementedPaxosNodeServer) ResetNode(context.Context, *ResetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetNode not implemented")
}
func (UnimplementedPaxosNodeServer) mustEmbedUnimplementedPaxosNodeServer() {}

// UnsafePaxosNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosNodeServer will
// result in compilation errors.
type UnsafePaxosNodeServer interface {
	mustEmbedUnimplementedPaxosNodeServer()
}

func RegisterPaxosNodeServer(s grpc.ServiceRegistrar, srv PaxosNodeServer) {
	s.RegisterService(&PaxosNode_ServiceDesc, srv)
}

func _PaxosNode_TransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).TransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_TransferRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).TransferRequest(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_ForwardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).ForwardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_ForwardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).ForwardRequest(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrepareRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrepareRequest(ctx, req.(*PrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_AcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).AcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_AcceptRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).AcceptRequest(ctx, req.(*AcceptMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_CommitRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).CommitRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_CommitRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).CommitRequest(ctx, req.(*CommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_CheckpointRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).CheckpointRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_CheckpointRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).CheckpointRequest(ctx, req.(*CheckpointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_NewViewRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NewViewMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaxosNodeServer).NewViewRequest(m, &paxosNodeNewViewRequestServer{stream})
}

type PaxosNode_NewViewRequestServer interface {
	Send(*AcceptedMessage) error
	grpc.ServerStream
}

type paxosNodeNewViewRequestServer struct {
	grpc.ServerStream
}

func (x *paxosNodeNewViewRequestServer) Send(m *AcceptedMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _PaxosNode_CatchupRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatchupRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).CatchupRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_CatchupRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).CatchupRequest(ctx, req.(*CatchupRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetCheckpoint(ctx, req.(*GetCheckpointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintLog(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintDB(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintView(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_ReconfigureNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.BoolValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).ReconfigureNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_ReconfigureNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).ReconfigureNode(ctx, req.(*wrapperspb.BoolValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_KillLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).KillLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_KillLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).KillLeader(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_ResetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).ResetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_ResetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).ResetNode(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosNode_ServiceDesc is the grpc.ServiceDesc for PaxosNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PaxosNode",
	HandlerType: (*PaxosNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferRequest",
			Handler:    _PaxosNode_TransferRequest_Handler,
		},
		{
			MethodName: "ForwardRequest",
			Handler:    _PaxosNode_ForwardRequest_Handler,
		},
		{
			MethodName: "PrepareRequest",
			Handler:    _PaxosNode_PrepareRequest_Handler,
		},
		{
			MethodName: "AcceptRequest",
			Handler:    _PaxosNode_AcceptRequest_Handler,
		},
		{
			MethodName: "CommitRequest",
			Handler:    _PaxosNode_CommitRequest_Handler,
		},
		{
			MethodName: "CheckpointRequest",
			Handler:    _PaxosNode_CheckpointRequest_Handler,
		},
		{
			MethodName: "CatchupRequest",
			Handler:    _PaxosNode_CatchupRequest_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _PaxosNode_GetCheckpoint_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _PaxosNode_PrintLog_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _PaxosNode_PrintDB_Handler,
		},
		{
			MethodName: "PrintStatus",
			Handler:    _PaxosNode_PrintStatus_Handler,
		},
		{
			MethodName: "PrintView",
			Handler:    _PaxosNode_PrintView_Handler,
		},
		{
			MethodName: "ReconfigureNode",
			Handler:    _PaxosNode_ReconfigureNode_Handler,
		},
		{
			MethodName: "KillLeader",
			Handler:    _PaxosNode_KillLeader_Handler,
		},
		{
			MethodName: "ResetNode",
			Handler:    _PaxosNode_ResetNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewViewRequest",
			Handler:       _PaxosNode_NewViewRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "paxos.proto",
}
